=== shiptest-ss13/Shiptest/_maps/ship_config_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"description": "The name of the ship class, as viewable in-game."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"description": "A shortened version of the ship class name, used in things such as the manifest.",
			"maxLength": 20
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": "string",
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"REVOLUTIONARY",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"MAGICAL"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.]*)dmm$"
		},
		"map_id": {
			"title": "Map ID (DEPRECATED)",
			"type": "string",
			"description": "The ID of the ship class. Deprecated, code uses map_path instead."
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"cost": {
			"title": "Class Cost",
			"type": "integer",
			"description": "The cost of the ship class, in credits.",
			"maximum": 116115990
		},
		"roundstart": {
			"title": "Random Roundstart Selection",
			"type": "boolean",
			"description": "Whether or not the ship has a chance to be randomly selected as the free roundstart ship.",
			"default": false
		}
	},

	"required": ["map_name", "map_path"]
}

=== shiptest-ss13/Shiptest/_maps/configs/statio.json
{
	"map_name": "Statio.3-class Station With Thrusters",
	"map_short_name": "Statio.3-class",
	"map_path": "_maps/shuttles/shiptest/nanotrasen_station.dmm",
	"map_id": "nanotrasen_station",
	"job_slots": {
		"Captain": 1,
		"Head of Personnel": 1,
		"Chief Engineer": 1,
		"Chief Medical Officer": 1,
		"Research Director": 1,
		"Head of Security": 1,
		"Solgov Representative": 1,
		"Station Engineer": 4,
		"Atmospheric Technician": 2,
		"Medical Doctor": 4,
		"Paramedic": 1,
		"Virologist": 1,
		"Chemist": 1,
		"Scientist": 4,
		"Roboticist": 2,
		"Quartermaster": 1,
		"Cargo Technician": 3,
		"Shaft Miner": 2,
		"Bartender": 1,
		"Cook": 1,
		"Botanist": 2,
		"Janitor": 1,
		"Chaplain": 1,
		"Clown": 1,
		"Mime": 1,
		"Warden": 1,
		"Detective": 1,
		"Brig Physician": 1,
		"Security Officer": 4,
		"Cyborg": 2,
		"Assistant": 30
	},
	"cost": 100000
}

=== shiptest-ss13/Shiptest/_maps/configs/tranq.json
{
	"map_name": "Tranquility-class Flying Apartment Complex",
	"prefix": "ISV",
	"namelists": ["GENERAL", "SPACE", "NATURAL"],
	"map_short_name": "Tranquility-class",
	"map_path": "_maps/shuttles/shiptest/tranq.dmm",
	"map_id": "tranq",
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/western",
			"officer": true,
			"slots": 1
		},
		"Scholar": {
			"outfit": "/datum/outfit/job/curator/librarian",
			"slots": 1
		},
		"Medical Tenant": {
			"outfit": "/datum/outfit/job/chemist/pharmacologist",
			"slots": 1
		},
		"Engineering Tenant": {
			"outfit": "/datum/outfit/job/engineer/electrician",
			"slots": 1
		},
		"Tenant": {
			"outfit": "/datum/outfit/job/curator/dungeonmaster",
			"slots": 1
		},
		"Resident Artist": {
			"outfit": "/datum/outfit/job/assistant/artist",
			"slots": 1
		}
	},
	"cost": 1000
}

=== shiptest-ss13/Shiptest/_maps/configs/SYN-C_courage-VOID.json
{
	"map_name": "Courage-class Strike Dropship",
	"map_short_name": "Courage-class",
	"prefix": "SYN-C",
	"map_path": "_maps/shuttles/shiptest/courage.dmm",
	"map_id": "courage_class",
	"job_slots": {
		"Syndicate Strike Captain": {
			"outfit": "/datum/outfit/syndicate_empty/sbc/assault/captain",
			"officer": true,
			"slots": 1
		},
		"Syndicate Marine":{
			"outfit": "/datum/outfit/syndicate_empty/sbc/assault",
			"slots": 3
		}
	},
	"cost": 750
}

=== shiptest-ss13/Shiptest/_maps/configs/independent_arrowhead.json
{
	"map_name": "Arrowhead-class Long Range Scoutship",
	"prefix": "ISV",
	"namelists": ["GENERAL", "SPACE", "MYTHOLOGICAL"],
	"map_short_name": "Arrowhead-class",
	"map_path": "_maps/shuttles/shiptest/independent_arrowhead.dmm",
	"map_id": "independent_arrowhead",
	"roundstart": true,
	"job_slots": {
		"Captain": 1,
		"Medical Doctor": 1,
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/engineer",
			"slots": 1
		},
		"Field Surveyor": {
			"outfit": "/datum/outfit/job/miner/hazard",
			"slots": 1
		},
		"Deckhand": {
			"outfit": "/datum/outfit/job/assistant",
			"slots": 2
		}
	},
	"cost": 600
}

=== shiptest-ss13/Shiptest/_maps/configs/meta.json
{
	"map_name": "Meta-class Freighter",
	"map_short_name": "Meta-class",
	"map_path": "_maps/shuttles/whiteship_meta.dmm",
	"map_id": "whiteship_meta",
	"job_slots": {
		"Captain": 1,
		"Quartermaster": 1,
		"Medical Doctor": 1,
		"Station Engineer": 1,
		"Shaft Miner": 1,
		"Assistant": 3
	},
	"cost": 500
}

=== shiptest-ss13/Shiptest/_maps/configs/deserter_rigger.json
{
	"map_name": "Rigoureux(D)-class Auxiliary Cutter",
	"map_short_name": "Rigoureux(D)-class",
	"map_path": "_maps/shuttles/shiptest/rigger_c.dmm",
	"map_id": "rigger_c",
	"roundstart": true,
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/solgov/rebel",
			"officer": true,
			"slots": 1
		},
		"Executive Officer": {
			"outfit": "/datum/outfit/job/head_of_personnel/solgov/rebel",
			"officer": true,
			"slots": 1
		},
		"Signal Officer": {
			"outfit": "/datum/outfit/job/solgov/rebel",
			"officer": true,
			"slots": 1
		},
		"Naval Surgeon": {
			"outfit": "/datum/outfit/job/doctor/solgov/rebel",
			"slots": 1
		},
		"Machinist": {
			"outfit": "/datum/outfit/job/engineer/solgov/rebel",
			"slots": 2
		},
		"Miner": {
			"outfit": "/datum/outfit/job/miner/solgov/rebel",
			"slots": 2
		},
		"Cook": 1,
		"Boarding Specialist": {
			"outfit": "/datum/outfit/job/security/solgov/rebel",
			"slots": 3
		},
		"Sailor": {
			"outfit": "/datum/outfit/job/assistant/solgov/rebel",
			"slots": 4
		}
	},
	"cost": 750
}

=== shiptest-ss13/Shiptest/_maps/configs/spitfire.json
{
	"map_name": "Spitfire-class Search and Rescue Vessel",
	"map_short_name": "Spitfire-class",
	"map_path": "_maps/shuttles/shiptest/syndicate_spitfire.dmm",
	"map_id": "syndicate_spitfire",
	"job_slots": {
		"Chief Medical Officer": 1,
		"Medical Doctor": 1,
		"Paramedic": 1,
		"Station Engineer": 1,
		"Shaft Miner": 1,
		"Assistant": 1
	},
	"cost": 350
}

=== shiptest-ss13/Shiptest/_maps/configs/cricket.json
{
	"map_name": "Cricket-Class Solgov Intel Scout",
	"map_short_name": "Solgov Cricket",
	"map_path": "_maps/shuttles/shiptest/solgov_cricket.dmm",
	"map_id" : "solgov_cricket",
	"job_slots": {
		"Captain": 1,
		"SolGov Representative": 1,
		"Chemist": 1,
		"Station Engineer": 2,
		"Shaft Miner": 2,
		"Cargo Technician": 1,
		"Security Officer": 1,
		"Cook": 1,
		"Assistant": 3
	},
	"cost": 780
}
