=== shiptest-ss13/Shiptest/_maps/ship_config_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"description": "The name of the ship class, as viewable in-game."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"description": "A shortened version of the ship class name, used in things such as the manifest.",
			"maxLength": 20
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": "string",
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"REVOLUTIONARY",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"MAGICAL"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.]*)dmm$"
		},
		"map_id": {
			"title": "Map ID (DEPRECATED)",
			"type": "string",
			"description": "The ID of the ship class. Deprecated, code uses map_path instead."
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"cost": {
			"title": "Class Cost",
			"type": "integer",
			"description": "The cost of the ship class, in credits.",
			"maximum": 116115990
		},
		"roundstart": {
			"title": "Random Roundstart Selection",
			"type": "boolean",
			"description": "Whether or not the ship has a chance to be randomly selected as the free roundstart ship.",
			"default": false
		}
	},

	"required": ["map_name", "map_path"]
}

=== shiptest-ss13/Shiptest/_maps/configs/solgov_liberty.json
{
	"map_name": "Liberty-class Interceptor",
	"map_short_name": "Liberty-class",
	"map_path": "_maps/shuttles/shiptest/solgov_liberty.dmm",
	"map_id": "liberty",
	"job_slots": {
		"Captain": 1,
		"Head of Personnel": 1,
		"Security Officer": 2,
		"Warden": 1,
		"Brig Physician": 1,
		"Staff Assistant": 4
	}
}

=== shiptest-ss13/Shiptest/_maps/configs/scrapper.json
{
	"map_name": "Scrapper-Class Salvage Cruiser",
	"map_short_name": "Scrapper",
	"map_path": "_maps/shuttles/shiptest/scrapper.dmm",
	"map_id": "scrapper",
	"job_slots": {
		"Captain": 1,
		"Head of Personnel": 1,
		"Medical Doctor": 4,
		"Station Engineer": 3,
		"Shaft Miner": 3,
		"Security Officer": 2,
		"Assistant": 7,
		"Botanist": 1
	},
	"cost": 750
}

=== shiptest-ss13/Shiptest/_maps/configs/twinkleshine.json
{
	"map_name": "Twinkleshine-class Battle Cruiser",
	"map_short_name": "Twinkleshine-class",
	"map_path": "_maps/shuttles/shiptest/starfury_class.dmm",
	"map_id": "starfury_class",
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/syndicate_empty/sbc/assault/captain",
			"officer": true,
			"slots": 1
		},
		"Operative": {
			"outfit": "/datum/outfit/syndicate_empty/sbc/assault/operative",
			"officer": true,
			"slots": 1
		},
		"Medic":{
			"outfit": "/datum/outfit/syndicate_empty/sbc/med",
			"slots": 2
		},
		"Mechanic":{
			"outfit": "/datum/outfit/syndicate_empty/sbc/engi",
			"slots": 2
		},
		"Trooper":{
			"outfit": "/datum/outfit/syndicate_empty/sbc/assault",
			"slots": 5
		},
		"Deck Assistant":{
			"outfit": "/datum/outfit/syndicate_empty/sbc",
			"slots": 2
		}
	}
}

=== shiptest-ss13/Shiptest/_maps/configs/delta.json
{
	"map_name": "Delta-class Frigate",
	"map_short_name": "Delta-class",
	"map_path": "_maps/shuttles/whiteship_delta.dmm",
	"map_id": "whiteship_delta",
	"job_slots": {
		"Captain": 1,
		"Quartermaster": 1,
		"Medical Doctor": 1,
		"Station Engineer": 1,
		"Shaft Miner": 1,
		"Assistant": 3
	},
	"cost": 500
}

=== shiptest-ss13/Shiptest/_maps/configs/goon.json
{
	"map_name": "Goon-class Repurposed Emergency Shuttle",
	"map_short_name": "Goon-class",
	"map_path": "_maps/shuttles/shiptest/nanotrasen_goon.dmm",
	"map_id": "nanotrasen_goon",
	"job_slots": {
		"Captain": 1,
		"Shaft Miner": 1,
		"Station Engineer": 1,
		"Medical Doctor": 1,
		"Assistant": 3
	},
	"cost": 300
}

=== shiptest-ss13/Shiptest/_maps/configs/shetland.json
{
	"map_name": "Shetland-class Multipurpose Frigate",
	"map_short_name": "Shetland-class",
	"map_path": "_maps/shuttles/amogus_sus.dmm",
	"map_id": "amogus_sus",
	"roundstart": true,
	"job_slots": {
		"Captain": 1,
		"SolGov Representative": 1,
		"Head of Personnel": 1,
		"Medical Doctor": 2,
		"Station Engineer": 3,
		"Shaft Miner": 2,
		"Cargo Technician": 2,
		"Security Officer": 1,
		"Assistant": 5
	},
	"cost": 750
}

=== shiptest-ss13/Shiptest/_maps/configs/solgov_rigger.json
{
	"map_name": "Rigoureux-class Auxiliary Cutter",
	"map_short_name": "Rigoureux-class",
	"map_path": "_maps/shuttles/shiptest/rigger_b.dmm",
	"map_id": "rigger_b",
	"roundstart": true,
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/solgov",
			"officer": true,
			"slots": 1
		},
		"Executive Officer": {
			"outfit": "/datum/outfit/job/head_of_personnel/solgov",
			"officer": true,
			"slots": 1
		},
		"Signal Officer": {
			"outfit": "/datum/outfit/job/solgov",
			"officer": true,
			"slots": 1
		},
		"Naval Surgeon": {
			"outfit": "/datum/outfit/job/doctor/solgov",
			"slots": 1
		},
		"Machinist": {
			"outfit": "/datum/outfit/job/engineer/solgov",
			"slots": 2
		},
		"Pioneer": {
			"outfit": "/datum/outfit/job/miner/solgov",
			"slots": 2
		},
		"Cook": 1,
		"Brig Officer": {
			"outfit": "/datum/outfit/job/warden/solgov",
			"slots": 1
		},
		"Boarding Specialist": {
			"outfit": "/datum/outfit/job/security/solgov",
			"slots": 2
		},
		"Sailor": {
			"outfit": "/datum/outfit/job/assistant/solgov",
			"slots": 4
		}
	},
	"cost": 750
}

=== shiptest-ss13/Shiptest/_maps/configs/pubby.json
{
	"map_name": "Pubby-class Light Carrier",
	"map_short_name": "Punny-class",
	"map_path": "_maps/shuttles/whiteship/whiteship_pubby.dmm",
	"map_id": "whiteship_pubby",
	"job_slots": {
		"Captain": 1,
		"Quartermaster": 1,
		"Medical Doctor": 1,
		"Station Engineer": 1,
		"Shaft Miner": 2,
		"Assistant": 2
	},
	"cost": 500
}
