=== shiptest-ss13/Shiptest/_maps/ship_config_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"description": "The name of the ship class, as viewable in-game."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"description": "A shortened version of the ship class name, used in things such as the manifest.",
			"maxLength": 20
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": "string",
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"REVOLUTIONARY",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"MAGICAL"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.]*)dmm$"
		},
		"map_id": {
			"title": "Map ID (DEPRECATED)",
			"type": "string",
			"description": "The ID of the ship class. Deprecated, code uses map_path instead."
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"cost": {
			"title": "Class Cost",
			"type": "integer",
			"description": "The cost of the ship class, in credits.",
			"maximum": 116115990
		},
		"roundstart": {
			"title": "Random Roundstart Selection",
			"type": "boolean",
			"description": "Whether or not the ship has a chance to be randomly selected as the free roundstart ship.",
			"default": false
		}
	},

	"required": ["map_name", "map_path"]
}

=== shiptest-ss13/Shiptest/_maps/configs/dwayne.json
{
	"map_name": "Dwayne-class Long Range Mining Transport",
	"prefix": "SV",
	"namelists": ["GENERAL", "SPACE", "NATURAL", "MERCANTILE"],
	"map_short_name": "Dwayne-class",
	"map_path": "_maps/shuttles/shiptest/mining_ship_all.dmm",
	"map_id": "mining_ship",
	"roundstart": true,
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/western",
			"officer": true,
			"slots": 1
		},
		"Foreman": {
			"outfit": "/datum/outfit/job/quartermaster/western",
			"slots": 1
			},
		"Ship's Doctor": {
			"outfit": "/datum/outfit/job/doctor",
			"slots": 1
			},
		"Ship's Engineer": {
			"outfit": "/datum/outfit/job/engineer/hazard",
			"slots": 1
		},
		"Asteroid Miner": {
			"outfit": "/datum/outfit/job/miner/hazard",
			"slots": 2
		},
		"Deckhand": {
			"outfit": "/datum/outfit/job/assistant",
			"slots": 3
		}
	},
	"cost": 500
}

=== shiptest-ss13/Shiptest/_maps/configs/golem.json
{
	"map_name": "Prague-Class Independent Research Vessel",
	"map_short_name": "Prague-Class",
	"map_path": "_maps/shuttles/shiptest/golem_ship.dmm",
	"map_id": "golem_ship",
	"job_slots": {
		"Captain": 1,
		"Head of Personnel": 1,
		"Medical Doctor": 2,
		"Station Engineer": 3,
		"Shaft Miner": 2,
		"Cargo Technician": 2,
		"Security Officer": 1,
		"Assistant": 5
	}
}

=== shiptest-ss13/Shiptest/_maps/configs/luxembourg.json
{
	"map_name": "Luxembourg-class Delivery Vessel",
	"map_short_name": "Luxembourg-class",
	"map_path": "_maps/shuttles/shiptest/syndicate_luxembourg.dmm",
	"map_id": "syndicate_luxembourg",
	"job_slots": {
		"Quartermaster": 1,
		"Cargo Technician": 2,
		"Station Engineer": 1,
		"Assistant": 3,
		"Bartender": 1,
		"Medical Doctor": 1
	},
	"cost": 600
}

=== shiptest-ss13/Shiptest/_maps/configs/corphigh.json
{
	"map_name": "High-class corporate luxury ship",
	"map_short_name": "High-class",
	"map_path": "_maps/shuttles/shiptest/corp_high.dmm",
	"map_id": "corp_high",
	"job_slots": {
		"Captain": 1,
		"Security Officer": 2,
		"Station Engineer": 1,
		"Shaft Miner": 1,
		"Assistant": 4
	},
	"cost": 850
}

=== shiptest-ss13/Shiptest/_maps/configs/gorlex_hyena.json
{	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"prefix": "SSV",
	"namelists": ["GENERAL", "NATURAL_AGGRESSIVE", "BEASTS", "WEAPONS"],
	"map_name": "Hyena-class Wrecking Tug",
	"map_short_name": "Hyena-class",
	"map_path": "_maps/shuttles/shiptest/gorlex_hyena.dmm",
	"map_id": "gorlex_hyena",
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/syndicate/gorlex",
			"officer": true,
			"slots": 1
		},
		"Foreman": {
			"outfit": "/datum/outfit/job/ce/syndicate/gorlex",
			"officer": true,
			"slots": 1
		},
		"Mechanic": {
			"outfit": "/datum/outfit/job/engineer/syndicate/gorlex",
			"slots": 1
		},
		"Wrecker": {
			"outfit": "/datum/outfit/job/miner/syndicate",
			"slots": 2
		},
		"Junior Agent": {
			"outfit": "/datum/outfit/job/assistant/syndicate/gorlex",
			"slots": 2
		}
	},
	"cost": 750
}

=== shiptest-ss13/Shiptest/_maps/configs/independent_halftrack.json
{
	"$schema": "https://raw.githubusercontent.com/ZetaSingularity/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Halftrack-Class Merchant Vessel",
	"prefix": "ISV",
	"namelists": ["MERCANTILE", "WEAPONS"],
	"map_short_name": "Halftrack-Class",
	"map_path": "_maps/shuttles/shiptest/independent_halftrack.dmm",
	"cost": 0,
	"job_slots": {
		"Captain": 1,
		"IRMG Vanguard": {
			"outfit": "/datum/outfit/job/captain/inteq",
			"officer": true,
			"slots": 1
		},
		"IRMG Enforcer": {
			"outfit": "/datum/outfit/job/security/inteq",
			"slots": 2
		}
	}
}

=== shiptest-ss13/Shiptest/_maps/configs/raven.json
{
	"map_name": "Raven-class Heavy Transporter",
	"map_short_name": "Raven-class",
	"map_path": "_maps/shuttles/shiptest/nanotrasen_raven.dmm",
	"map_id": "nanotrasen_raven",
	"job_slots": {
		"Captain": 1,
		"Head of Security": 1,
		"Chief Medical Officer": 1,
		"Head Of Personnel": 1,
		"Chief Engineer": 1,
		"Station Engineer": 1,
		"Security Officer": 1,
		"Shaft Miner": 1,
		"Medical Doctor": 1,
		"Cargo Technician": 1,
		"Assistant": 3
	},
	"cost": 650
}

=== shiptest-ss13/Shiptest/_maps/configs/kilo.json
{
	"map_name": "Kilo-class Mining Ship",
	"prefix": "SV",
	"namelists": ["GENERAL", "SPACE", "NATURAL", "NATURAL_AGGRESSIVE"],
	"map_short_name": "Kilo-class",
	"map_path": "_maps/shuttles/shiptest/whiteship_kilo.dmm",
	"map_id": "whiteship_kilo",
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/captain/western",
			"officer": true,
			"slots": 1
		},
		"Foreman": {
			"outfit": "/datum/outfit/job/quartermaster/western",
			"slots": 1
			},
		"Ship's Doctor": {
			"outfit": "/datum/outfit/job/doctor",
			"slots": 1
			},
		"Ship's Engineer": {
			"outfit": "/datum/outfit/job/engineer/hazard",
			"slots": 1
		},
		"Asteroid Miner": {
			"outfit": "/datum/outfit/job/miner/hazard",
			"slots": 2
		},
		"Deckhand": {
			"outfit": "/datum/outfit/job/assistant",
			"slots": 2
		}
	},
	"cost": 500
}
